<?php

/**
 * @file
 * Contains flexslider_field_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flexslider_field_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flexslider_field_formatter module.
    case 'help.page.flexslider_field_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FlexSlider Field Formatter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function flexslider_field_formatter_theme($existing, $type, $theme, $path) {
  return [
    'flexslider_field_formatter' => [
      'render element' => 'elements',
      'variables' => [
        'show_carousel' => NULL,
        'items' => NULL,
      ],
      'file' => 'flexslider_field_formatter.theme.inc',
    ],
  ];
}
